export const cityData = [
    {
        Name:"不分區域",
        engName:"all",
    },
    {
        Name:"台北市",
        engName:"Taipei",
    },
    {
        Name:"新北市",
        engName:"NewTaipei",
    },
    {
        Name:"桃園市",
        engName:"Taoyuan",
    },
    {
        Name:"台中市",
        engName:"Taichung",
    },
    {
        Name:"台南市",
        engName:"Tainan",
    },
    {
        Name:"高雄市",
        engName:"Kaohsiung",
    },
    {
        Name:"基隆市",
        engName:"Keelung",
    },
    {
        Name:"新竹市",
        engName:"Hsinchu",
    },
    {
        Name:"苗栗縣",
        engName:"MiaoliCounty",
    },
    {
        Name:"彰化縣",
        engName:"ChanghuaCounty",
    },
    {
        Name:"南投縣",
        engName:"NantouCounty",
    },
    {
        Name:"雲林縣",
        engName:"YunlinCounty",
    },
    {
        Name:"嘉義縣",
        engName:"ChiayiCounty",
    },
    {
        Name:"嘉義市",
        engName:"Chiayi",
    },
    {
        Name:"屏東縣",
        engName:"PingtungCounty",
    },
    {
        Name:"宜蘭縣",
        engName:"YilanCounty",
    },
    {
        Name:"花蓮縣",
        engName:"HualienCounty",
    },
    {
        Name:"台東縣",
        engName:"TaitungCounty",
    },
    {
        Name:"金門縣",
        engName:"KinmenCounty",
    },
    {
        Name:"澎湖縣",
        engName:"PenghuCounty",
    },
    {
        Name:"連江縣",
        engName:"LienchiangCounty",
    }
]